###consul服务端口号
server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.6.180
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        #不要用localhost，服务器上的consul server找不到localhost，要配置成本地服务地址192.168.1.109
        health-check-url: http://192.168.1.109:80/actuator/health

